apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: bookverse
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo